### ISSUE TITLE
Crashes in Emulator

### ISSUE THREAD

**Issue by TheSR007** [artdeell/Canvas-Open-Source#2]
Upon Checking the log, it seems the apk tries to run in x86 mode and then shifts to x86_64 mode rather than arm64-v8a. It crashes because there isn't necessary libs in x64 arch so I tried to compile in x64 and libkeystone.a wasn't available in x64 and got that from github but shadowhook only supports Thumb, arm and arm64. Logcat has been provided. 
[canvas.log](https://github.com/artdeell/Canvas-Open-Source/files/14864634/canvas.log)

**Comment by RomanChamelo** [comment]
yeah i think Mumu has a problem to run canvas there and also a memory patched. maybe i gonna remove keystone and shadow hook because it unnecessary needed.

**Comment by Kiojeen** [comment]
This is a problem with the emulator itself (MUMU). Try renaming the package of canvas to something like com.tgc.sky.canvas and it will work.

**Comment by TheSR007** [comment]
It's an weird issue, The problem wasn't exactly with the canvas, I was running in Vulkan in MUMU but canvas would still crash but as kio mentioned it starts to work if you rename the package name(I tried to rename wilth APKtoolM but there was an issue but after updating the APktoolM it worked after renaming)
MUMU's picture
![image](https://github.com/artdeell/Canvas-Open-Source/assets/101653309/8f116296-8b9c-4871-b556-741059387da0)
I also tried without renaming the package in Bluestacks but crashed(reason is I was running in OpenGl, only works in Vulkan)
and Bluestacks
![image](https://github.com/artdeell/Canvas-Open-Source/assets/101653309/9e5d0abf-92a2-4c2a-b908-5314047dedd4)

**Comment by TheSR007** [comment]
It's an weird issue, The problem wasn't exactly with the canvas, I was running in Vulkan in MUMU but canvas would still crash but as kio mentioned it starts to work if you rename the package name(I tried to rename wilth APKtool M but there was an issue but after updating the APktool M it worked after renaming)
MUMU's picture
![image](https://github.com/artdeell/Canvas-Open-Source/assets/101653309/8f116296-8b9c-4871-b556-741059387da0)
I also tried without renaming the package in Bluestacks but crashed(reason is I was running in OpenGl, only works in Vulkan) it works with/without renaming in Bluestacks only in Vulkan and works in DirectX and Vulkan with renaming in MUMU
Bluestacks's Image
![image](https://github.com/artdeell/Canvas-Open-Source/assets/101653309/9e5d0abf-92a2-4c2a-b908-5314047dedd4)

**Conclusion**: If you are facing crash check your Graphics rendered if it's Vulkan or not, make it Vulkan and if you are using MUMU renaming the package seems to solve the crash even in DirectX
